import numpy as np
from scrapy import Item, Field

class PingshanDemandData(Item):
    _id = Field()
    REPORT_NUM = Field()
    EVENT_PROPERTY_NAME = Field()
    EVENT_TYPE_ID = Field()
    EVENT_TYPE_NAME = Field()
    EVENT_SRC_NAME = Field()
    DISTRICT_ID = Field()
    INTIME_ARCHIVE_NUM = Field()
    SUB_TYPE_ID = Field()
    DISTRICT_NAME = Field()
    COMMUNITY_ID = Field()
    REC_ID = Field()
    STREET_ID = Field()
    OVERTIME_ARCHIVE_NUM = Field()
    OPERATE_NUM = Field()
    DISPOSE_UNIT_ID = Field()
    STREET_NAME = Field()
    CREATE_TIME = Field()
    EVENT_SRC_ID = Field()
    INTIME_TO_ARCHIVE_NUM = Field()
    SUB_TYPE_NAME = Field()
    EVENT_PROPERTY_ID = Field()
    COMMUNITY_NAME = Field()
    DISPOSE_UNIT_NAME = Field()
    MAIN_TYPE_NAME = Field()
    MAIN_TYPE_ID = Field()

class PingshanPOIData(Item):
    _id = Field()
    POI_Id = Field()
    Name = Field()
    Type = Field()
    TypeNumber = Field()
    Trade = Field()
    Address = Field()
    Phone = Field()
    Longitute = Field()
    Latitude = Field()
    GPS = Field()
    Province = Field()
    City = Field()
    District = Field()